# @BAKE lighttpd -D -f $@
server.document-root = var.CWD
server.port = "8080"

server.modules += ( "mod_rewrite" )
url.rewrite-once = (
    "^/out/.*" => "$0",
    ".*"       => "/upchud.tcl"
)

# This limits the maximum upload size (in kbytes).
server.max-request-size = 204800 # 200 MiB

# This makes sure people cant inject Tcl scripts
server.modules += ( "mod_cgi" )
$HTTP["url"] == "/upchud.tcl" {
    cgi.assign = ( ".tcl" => "" )
}


debug.log-request-header      = 1
debug.log-file-not-found      = 1
debug.log-condition-handling  = 1
debug.log-request-handling    = 1
debug.log-state-handling      = 1
debug.log-response-header     = 1

server.errorlog = "errors.log"
